# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_20190509.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2620, 1500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1400, 840, 921, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 60, 61, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(320, 60, 51, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(640, 60, 51, 41))
        self.label_3.setObjectName("label_3")
        self.z_text = QtWidgets.QTextBrowser(self.groupBox)
        self.z_text.setGeometry(QtCore.QRect(690, 60, 191, 61))
        self.z_text.setObjectName("z_text")
        self.y_text = QtWidgets.QTextBrowser(self.groupBox)
        self.y_text.setGeometry(QtCore.QRect(370, 60, 211, 61))
        self.y_text.setObjectName("y_text")
        self.x_text = QtWidgets.QTextBrowser(self.groupBox)
        self.x_text.setGeometry(QtCore.QRect(80, 60, 201, 61))
        self.x_text.setObjectName("x_text")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1400, 1000, 921, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.thetaz_text = QtWidgets.QTextBrowser(self.groupBox_2)
        self.thetaz_text.setGeometry(QtCore.QRect(690, 50, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.thetaz_text.setFont(font)
        self.thetaz_text.setObjectName("thetaz_text")
        self.thetay_text = QtWidgets.QTextBrowser(self.groupBox_2)
        self.thetay_text.setGeometry(QtCore.QRect(370, 50, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.thetay_text.setFont(font)
        self.thetay_text.setObjectName("thetay_text")
        self.thetax_text = QtWidgets.QTextBrowser(self.groupBox_2)
        self.thetax_text.setGeometry(QtCore.QRect(80, 50, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.thetax_text.setFont(font)
        self.thetax_text.setObjectName("thetax_text")
        self.Stream_PushBt = QtWidgets.QPushButton(self.centralwidget)
        self.Stream_PushBt.setGeometry(QtCore.QRect(1430, 1180, 250, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Stream_PushBt.setFont(font)
        self.Stream_PushBt.setObjectName("Stream_PushBt")
        self.Init_PushBt = QtWidgets.QPushButton(self.centralwidget)
        self.Init_PushBt.setGeometry(QtCore.QRect(1730, 1180, 250, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Init_PushBt.setFont(font)
        self.Init_PushBt.setObjectName("Init_PushBt")
        self.DepthFrame = QtWidgets.QLabel(self.centralwidget)
        self.DepthFrame.setGeometry(QtCore.QRect(20, 760, 1280, 720))
        self.DepthFrame.setText("")
        self.DepthFrame.setObjectName("DepthFrame")
        self.ResultFrame = QtWidgets.QLabel(self.centralwidget)
        self.ResultFrame.setGeometry(QtCore.QRect(1320, 20, 1280, 720))
        self.ResultFrame.setText("")
        self.ResultFrame.setObjectName("ResultFrame")
        self.detect_PushBt = QtWidgets.QPushButton(self.centralwidget)
        self.detect_PushBt.setGeometry(QtCore.QRect(2030, 1180, 250, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detect_PushBt.setFont(font)
        self.detect_PushBt.setObjectName("detect_PushBt")
        self.RGBFrame = QtWidgets.QLabel(self.centralwidget)
        self.RGBFrame.setGeometry(QtCore.QRect(20, 20, 1280, 720))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.RGBFrame.setFont(font)
        self.RGBFrame.setText("")
        self.RGBFrame.setObjectName("RGBFrame")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(1400, 1300, 951, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.Mind_Edit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.Mind_Edit.setGeometry(QtCore.QRect(100, 70, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mind_Edit.setFont(font)
        self.Mind_Edit.setObjectName("Mind_Edit")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 81, 31))
        self.label_4.setObjectName("label_4")

        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)

        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(260, 70, 81, 31))
        self.label_5.setObjectName("label_5")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.Maxd_Edit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.Maxd_Edit.setGeometry(QtCore.QRect(340, 70, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Maxd_Edit.setFont(font)
        self.Maxd_Edit.setCursorWidth(1)
        self.Maxd_Edit.setObjectName("Maxd_Edit")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(510, 70, 111, 31))
        self.label_6.setObjectName("label_6")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.Scaled_Edit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.Scaled_Edit.setGeometry(QtCore.QRect(620, 70, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Scaled_Edit.setFont(font)
        self.Scaled_Edit.setCursorWidth(1)
        self.Scaled_Edit.setObjectName("Scaled_Edit")
        self.Set_PushBt = QtWidgets.QPushButton(self.groupBox_3)
        self.Set_PushBt.setGeometry(QtCore.QRect(800, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Set_PushBt.setFont(font)
        self.Set_PushBt.setObjectName("Set_PushBt")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.Stream_PushBt.raise_()
        self.Init_PushBt.raise_()
        self.DepthFrame.raise_()
        self.ResultFrame.raise_()
        self.detect_PushBt.raise_()
        self.RGBFrame.raise_()
        self.groupBox_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2620, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Detected Object Center (mm)"))
        self.label.setText(_translate("MainWindow", "X:"))
        self.label_2.setText(_translate("MainWindow", "Y:"))
        self.label_3.setText(_translate("MainWindow", "Z:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Grasping Pose"))
        self.Stream_PushBt.setText(_translate("MainWindow", "Start Stream"))
        self.Init_PushBt.setText(_translate("MainWindow", "Init Gripper"))
        self.detect_PushBt.setText(_translate("MainWindow", "Detect"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Depth Visualization (mm)"))
        self.Mind_Edit.setPlainText(_translate("MainWindow", "450"))
        self.label_4.setText(_translate("MainWindow", "min:"))
        self.label_5.setText(_translate("MainWindow", "max:"))
        self.Maxd_Edit.setPlainText(_translate("MainWindow", "600"))
        self.label_6.setText(_translate("MainWindow", "scale:"))
        self.Scaled_Edit.setPlainText(_translate("MainWindow", "1"))
        self.Set_PushBt.setText(_translate("MainWindow", "Set"))


